repo_names:
  - dckr

regex_rules:
  "test-.*":
    # retention_days: 7
    reserved: 2

  #"dev-latest.*":
  #  min_days_since_last_download: 1


  "^release-.*":
    #retention_days: 1
    reserved: 1

  "dev-latest.*":
    retention_days: 14
    #reserved: 1
    min_days_since_last_download: 14
  


# Для всех, кто не попал под regex_rules
#no_match_retention_days: 12
#no_match_reserved: 1
#no_match_min_days_since_last_download: 2


dry_run: true