repo_names:
  - maven2-test1

maven_rules:
  snapshot:
    regex_rules:
      ".*":
        min_days_since_last_download: 1

  # глобальные правила no-match (работают и для snapshot, и для release)
    no_match_reserved: 10

dry_run: true
