services:
  # MinIO Instance 1
  minio1:
    image: quay.io/minio/minio:latest
    command: server --address ":9100" --console-address ":9101" http://minio{1...4}/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio1-data:/data
    networks:
      - minio-net

  # MinIO Instance 2
  minio2:
    image: quay.io/minio/minio:latest
    command: server --address ":9100" --console-address ":9101" http://minio{1...4}/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio2-data:/data
    networks:
      - minio-net

  # MinIO Instance 3
  minio3:
    image: quay.io/minio/minio:latest
    command: server --address ":9100" --console-address ":9101" http://minio{1...4}/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio3-data:/data
    networks:
      - minio-net

  # MinIO Instance 4
  minio4:
    image: quay.io/minio/minio:latest
    command: server --address ":9100" --console-address ":9101" http://minio{1...4}/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio4-data:/data
    networks:
      - minio-net

  # HAProxy for MinIO Load Balancing
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8200:9100"  # MinIO API (внутри контейнера 9000, снаружи 8200)
      - "8201:9101"  # MinIO Console (внутри контейнера 9001, снаружи 8201)
    networks:
      - minio-net
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  # Nexus Repository Manager
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "9090:8081"   # Nexus Web UI (внутри контейнера 8081, снаружи 9090)
      - "8082:8082"   # Docker repository HTTP остается без изменений
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx2048m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data
    networks:
      - minio-net

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  nexus-data:

networks:
  minio-net:
