services:
  nexus:
    image: sonatype/nexus3:3.83.2
    restart: unless-stopped
    container_name: nexus
    volumes:
      - ./volume/nexus-data:/nexus-data
    ports:
      - "9090:8081"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data
    networks:
      - minio-net
    depends_on:
      - postgres
      - minio-single

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volume/pg_data:/var/lib/postgresql/data
    networks:
      - minio-net

  minio-single:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - ./volume/minio-single-data:/data
    networks:
      - minio-net

  vector:
    image: timberio/vector:latest-alpine
    container_name: vector
    restart: unless-stopped
    volumes:
      - ./volume/nexus-data/log/audit:/var/log/nexus_audit:ro
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    environment:
      - VECTOR_LOG=info
    networks:
      - minio-net

networks:
  minio-net:
    external: true
    name: transfer_minio-net
