services:
  haproxy:
    image: haproxy:latest
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8200:9100"
      - "8201:9101"
    depends_on:
      - minio-single
    networks:
      - minio-net

  nexus:
    image: sonatype/nexus3:3.82.0
    restart: unless-stopped
    container_name: nexus
    volumes:
      - ./volume/nexus-data:/nexus-data
    ports:
      - "9090:8081"
      - "5000-5030:5000-5030"
      - "8082-8090:8082-8090"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data
    networks:
      - minio-net
    depends_on:
      - postgres
      - minio-single

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volume/pg_data:/var/lib/postgresql/data


  minio-single:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - ./volume/minio-single-data:/data
    networks:
      - minio-net

  minio-replica:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9200:9000"
      - "9201:9001"
    volumes:
      - ./volume/minio-replica-data:/data
    networks:
      - minio-net


networks:
  minio-net:
