global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nexus'
    basic_auth:


    metrics_path: '/service/metrics/prometheus'
    static_configs:
      - targets: ['sanich.space', 'sanich.space:8000']

