global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nexus_customs"
    metrics_path: "/service/rest/metrics/prometheus"
    static_configs:
      - targets: ["sanich.tech:8000", "sanich.tech:8081"]
