global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nexus'
    static_configs:
      - targets: ['sanich.tech:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['sanich.tech:9210']



# docker run -d \
#   --name node_exporter \
#   -p 9210:9100 \
#   --restart unless-stopped \
#   prom/node-exporter

