- name: Получение всех проектов из GitLab группы с пагинацией
  hosts: all
  gather_facts: false

  vars:
    gitlab_url: "https://gitlab.ru"
    group_id: "3514"
    gitlab_token: "{{ gitlab_token }}"
    per_page: 100
    current_page: 1
    all_projects: []

  tasks:
    - name: Загружаем страницу {{ current_page }}
      uri:
        url: "{{ gitlab_url }}/api/v4/groups/{{ group_id }}/projects?per_page={{ per_page }}&page={{ current_page }}"
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ gitlab_token }}"
        return_content: true
      register: page_response
      until: page_response.json | length == 0
      retries: 50
      delay: 0

    - name: Добавляем все страницы в список
      set_fact:
        all_projects: "{{ all_projects + item.json }}"
      loop: "{{ page_response.results | default([]) }}"
      when: item.json | length > 0

    - name: Показать общее количество проектов
      debug:
        msg: "Всего проектов: {{ all_projects | length }}"

    - name: Показать первые 3 проекта
      debug:
        msg: "{{ all_projects[:3] | to_nice_json }}"
