- name: Загрузка конфигов для автоочистки Nexus
  hosts: all
  become: true
  gather_facts: false

  vars:
    group_id: "3514"
    gitlab_url: "https://gitlab.fc.uralsibbank.ru"
    gitlab_token: "{{ gitlab_token }}"
    branch: "main"
    file_path: "nexus/cleaner"
    dest_path: "/wdata/nexus/nexus-cleaner/configs"
    allowed_extensions:
      - ".yaml"
      - ".yml"

  tasks:
    - name: Получаем все проекты с пагинацией
      vars:
        all_projects: []
      block:
        - name: Загружаем страницы с проектами
          uri:
            url: "{{ gitlab_url }}/api/v4/groups/{{ group_id }}/projects?per_page=100&page={{ item }}"
            headers:
              PRIVATE-TOKEN: "{{ gitlab_token }}"
            return_content: true
          register: page_result
          loop: "{{ range(1, 20) | list }}"  # ограничим 20 страниц для безопасности
          until: page_result.json | length == 0
          retries: 1
          delay: 0

        - name: Объединяем результаты всех страниц
          set_fact:
            all_projects: "{{ all_projects + item.json }}"
          loop: "{{ page_result.results }}"
          when: item.json | length > 0

    - name: Показать общее количество проектов
      debug:
        msg: "Всего проектов: {{ all_projects | length }}"

    - name: Показать первые 3 проекта
      debug:
        msg: "{{ all_projects[:3] | to_nice_json }}"
