- name: Загрузка конфигов для автоочистки Nexus
  hosts: all
  become: true
  gather_facts: false

  vars:
    group_id: "3514"
    gitlab_url: "https://gitlab.fc.uralsibbank.ru"
    gitlab_token: "{{ gitlab_token }}"
    max_pages: 20  # ограничение для пагинации

  tasks:
    - name: Инициализация списка проектов
      set_fact:
        all_projects: []

    - name: Загружаем проекты постранично
      uri:
        url: "{{ gitlab_url }}/api/v4/groups/{{ group_id }}/projects?per_page=100&page={{ item }}"
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ gitlab_token }}"
        return_content: true
      register: gitlab_page
      loop: "{{ range(1, max_pages + 1) | list }}"
      until: gitlab_page.json | length == 0
      retries: 1
      delay: 0

    - name: Объединяем все страницы в один список
      set_fact:
        all_projects: "{{ all_projects + item.json }}"
      loop: "{{ gitlab_page.results }}"
      when: item.json | length > 0

    - name: Показать количество найденных проектов
      debug:
        msg: "Всего проектов: {{ all_projects | length }}"

    - name: Показать примеры проектов
      debug:
        msg: "{{ all_projects[:3] | to_nice_json }}"
