[sinks.graylog]
type = "gelf"
inputs = ["filter_audit"]
address = "147.45.132.70:12201" # или IP Graylog, если другой
compression = "none"

encoding.codec = "json"
encoding.only_fields = ["timestamp", "message", "appname", "hostname", "severity"]

# Преобразуем поля в GELF-совместимые
encoding.timestamp = "timestamp"
encoding.host = "hostname"
encoding.short_message = "message"
