---
- name: Clone or update config folder from Git on remote server
  hosts: test_server
  become: true
  gather_facts: true

  vars:
    git_repo_url: "https://github.com/SanichMyshkin/transfer"
    git_branch: "main"
    config_dir: "cleaner/configs"
    dest_path: "/root/configs"
    clone_path: "/opt/config_repo"  # изменил путь на постоянный

  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Clone or update Git repo on the server
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ clone_path }}"
        version: "{{ git_branch }}"
        force: yes  # нужен для перезаписи изменений

    - name: Copy config files to final destination
      ansible.builtin.command:
        cmd: cp -r "{{ clone_path }}/{{ config_dir }}/." "{{ dest_path }}/"
